services:
  pkelo-notice-web:
    image: ${PKELO_NOTICE_IMAGE:-ghcr.io/${GHCR_NAMESPACE:-neizzz}/pkelo-web:${IMAGE_TAG:-latest}}
    container_name: pkelo-notice-web-app
    networks:
      pkpkdupr-gateway:
        aliases:
          - pkelo-notice-web

networks:
  pkpkdupr-gateway:
    external: true
    name: ${GATEWAY_NETWORK:-pkpkdupr-gateway}
