services:
  pkelo-web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        VITE_APP_VERSION: ${VITE_APP_VERSION:-}

  pkelo-admin-web:
    build:
      context: .
      dockerfile: apps/admin-web/Dockerfile
      args:
        VITE_APP_VERSION: ${VITE_APP_VERSION:-}

  pkelo-api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile

  pkelo-db-server:
    build:
      context: .
      dockerfile: apps/db-server/Dockerfile
