services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-}

  admin-web:
    build:
      context: .
      dockerfile: apps/admin-web/Dockerfile

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile

  db-server:
    build:
      context: .
      dockerfile: apps/db-server/Dockerfile
