services:
  pkelo-certificate:
    image: linuxserver/swag:latest
    container_name: pkelo-certificate
    cap_add:
      - NET_ADMIN
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-Asia/Seoul}
      URL: ${DOMAIN:-pkelo.app}
      VALIDATION: dns
      DNSPLUGIN: cloudflare
      SUBDOMAINS: ""
    volumes:
      - ${PKPKDUPR_DEPLOY_PATH:-.}/data/pkelo-certs:/config
