FROM grafana/grafana:10.2.3

ENV GF_PATHS_PLUGINS=/opt/grafana-plugins

USER root

RUN mkdir -p "${GF_PATHS_PLUGINS}" \
  && grafana cli --pluginsDir "${GF_PATHS_PLUGINS}" plugins install frser-sqlite-datasource

USER grafana
