#!/bin/sh
set -eu

mysql --protocol=socket -uroot -p"${MYSQL_ROOT_PASSWORD}" <<SQL
CREATE USER IF NOT EXISTS '${MYSQL_VIEWER_USER}'@'%' IDENTIFIED BY '${MYSQL_VIEWER_PASSWORD}';
GRANT SELECT, SHOW VIEW ON \`${MYSQL_DATABASE}\`.* TO '${MYSQL_VIEWER_USER}'@'%';
FLUSH PRIVILEGES;
SQL
